# Generated by Django 3.0.2 on 2020-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about_the_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
