# Generated by Django 3.0.2 on 2020-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='saf', upload_to=''),
            preserve_default=False,
        ),
    ]
