# Generated by Django 3.0.2 on 2020-01-10 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries', to='accounts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_word', models.CharField(max_length=100)),
                ('en_word', models.CharField(max_length=100)),
                ('example', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, default='Необходимо повторить', max_length=50)),
                ('progress', models.IntegerField(default=1)),
                ('date_of_changes', models.DateTimeField(default=datetime.datetime(2020, 1, 10, 15, 15, 38, 389108, tzinfo=utc))),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_words', to='learning.Dictionary')),
            ],
        ),
    ]
