# Generated by Django 3.0.2 on 2020-01-14 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_of_changes',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 13, 23, 4, 898268, tzinfo=utc)),
        ),
    ]
