# Generated by Django 3.0.2 on 2020-01-14 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20200114_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ('title',), 'verbose_name': 'dictionary', 'verbose_name_plural': 'dictionaries'},
        ),
        migrations.AlterField(
            model_name='word',
            name='date_of_changes',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 14, 58, 5, 238564, tzinfo=utc)),
        ),
    ]
